[project]
name = "hello-web"
version = "0.1.0"
description = "Play with fastapi and react, running on pythonanywhere"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "gitpython>=3.1.44",
]
