name: Trigger Webhook on Push

on:
  push:
    branches:
      - main

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Update code on PythonAnywhere
        run: |
          curl --silent --fail-with-body -X POST https://${{ vars.PA_DOMAIN_NAME }}/update_server \
          -H 'Authorization: Token ${{ secrets.PA_API_TOKEN }}' \
          -H "Content-Type: application/json" \
          -d '{"update": "true"}'
    
      - name: Reload website on PythonAnywhere
        run: |
          curl --silent --fail-with-body -X POST \
          https://www.pythonanywhere.com/api/v1/user/${{ vars.PA_USERNAME }}/websites/${{ vars.PA_DOMAIN_NAME }}/reload/ \
          -H 'Authorization: Token ${{ secrets.PA_API_TOKEN }}'
