name: Trigger Webhook on Push

on:
  push:
    branches:
      - main

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Update code on PythonAnywhere
        run: |
          curl --silent --fail-with-body -X POST https://${{ vars.PA_DOMAIN_NAME }}/update_server \
          -H "Content-Type: application/json" \
          -d '{"update": "true"}'
      - name: Reload webapp on PythonAnywhere
        uses: jensvog/pythonanywhere-webapp-reload-action@v1
        with:
          host: 'eu.pythonanywhere.com'
          username: '${{ vars.PA_USERNAME }}'
          api-token: '${{ secrets.PA_API_TOKEN }}'
          domain-name: '${{ vars.PA_DOMAIN_NAME }}'
