name: Trigger Webhook on Push

on:
  push:
    branches:
      - main

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to FastAPI webhook
        run: |
          curl --silent --fail-with-body -X POST https://catac.pythonanywhere.com/update_server \
          -H "Content-Type: application/json" \
          -d '{"update": "true"}'
