name: Trigger Webhook on Push

on:
  push:
    branches:
      - main

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Update code on PythonAnywhere
        run: |
          curl --silent --fail-with-body -X POST ${{ vars.UPDATE_SERVER_URL }} \
          -H "Content-Type: application/json" \
          -d '{"update": "${{ secrets.UPDATE }}"}'
